export {
  CONFIG_DIR,
  CONFIG_ENV,
  loadConfig,
  APIError,
  HubSpotClient,
  getClient,
} from "./client.js";

export type {
  Filter,
  Sort,
  SearchOptions,
  SearchResult,
  ContactSearchOptions,
  CompanySearchOptions,
  DealSearchOptions,
  TicketSearchOptions,
  OrderSearchOptions,
  LineItemSearchOptions,
  CartSearchOptions,
  InvoiceSearchOptions,
  QuoteSearchOptions,
  SubscriptionSearchOptions,
} from "./hubspot.js";

export {
  listProperties,
  getAllPropertyNames,
  clearPropertyCache,
  searchObjects,
  getObject,
  searchContacts,
  getContact,
  searchCompanies,
  getCompany,
  searchDeals,
  getDeal,
  searchTickets,
  getTicket,
  searchProducts,
  getProduct,
  searchOrders,
  getOrder,
  searchLineItems,
  getLineItem,
  searchCarts,
  getCart,
  searchInvoices,
  getInvoice,
  searchQuotes,
  getQuote,
  searchSubscriptions,
  getSubscription,
} from "./hubspot.js";
